name: Publish Package

on:
  push:
    branches: [main]
    
  workflow_dispatch:

env:
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    HUSKY: 0

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions: 
      contents: write
      packages: write

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@anoguez'

      - name: Install Yarn
        run: |
          npm install -g yarn
          yarn set version berry
          yarn --version

      - name: Install dependencies
        run: yarn install

      - name: Build affected
        run: npx nx affected -t build

      - name: Run nx release
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          npx nx release && npx nx release publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}